language: php

matrix:
    include:
        - php: 5.6
        - php: 7.0
        - php: hhvm

script:
    - "php bin/phpunit -c phpunit.xml --colors=always --verbose --coverage-clover=coverage.xml"

after_success:
    - "bash <(curl -s https://codecov.io/bash)"
