language: "php"
php:
    - "5.5"
    - "5.6"
    - "7.0"
    - "7.1"    
    - "hhvm"

before_script:
    - "composer install --no-progress --no-interaction"

script:
    - "php bin/phpunit -c phpunit.xml --colors=always --verbose --coverage-clover=coverage.xml"

after_success:
    - "bash <(curl -s https://codecov.io/bash)"
